### ISSUE TITLE
bcbio_resources project not available on DNA Nexus?

### ISSUE THREAD

**Issue by dkrozelle** [geetduggal/bcbio-dnanexus-wrapper#7]
I've been using local install of bcbio for a bit now, thanks for this great resource. Trying to run this on DNAnexus now but having a bit of trouble, just wanted to get guidance on how to resolve. I can't seem to find the public **bcbio_resources** project on DNAnexus. Is this still available?

**Comment by geetduggal** [comment]
Hi @dkrozelle thanks for bringing this up!   @yihhwang @chapmanb and I are currently in the process of working to set this all up and make it available as a public app on DNAnexus and making that resources project public is indeed a part of our plan.   We will keep you posted.

**Comment by dkrozelle** [comment]
Awesome, need help on anything?

**Comment by geetduggal** [comment]
Not that I know of, but thanks for asking!

**Comment by waemm** [comment]
Hi guys, has this work been completed? I am not able to find bcbio_resources project on DNA nexus (AWS US (East). Any help would be greatly appreciated!

Thanks!
Warren
