### ISSUE TITLE
Can't find bcbio project on DNA Nexus

### ISSUE THREAD

**Issue by waemm** [geetduggal/bcbio-dnanexus-wrapper#8]
Hi,

I commented on an old post but I just wanted to check how to access the bcbio_resources project. I have followed your tutorial and I get the following error when I try to select the bcbio project

> PROJECT=project-F541fX00f5v9vKJjJ34gvgbv

>  dx select $PROJECT

> PermissionDenied: VIEW permission required in project-F541fX00f5v9vKJjJ34gvgbv to perform this action, code 401. Request Time=1562321823.97, Request ID=1562321824316-949418

Thanks!
Warren

**Comment by chapmanb** [comment]
Warren;
Sorry about this, the DNAnexus integration ended up getting stalled with my job change so would probably need some effort to keep moving forward. It might be a challenging way to go right now until we're able to spend more time on it. Apologies about not having it in a clean state.

**Comment by waemm** [comment]
Thanks Brad, much appreciated for your reply.
